### ISSUE TITLE
Error: <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Log in - SpigotMC Stash</title><script>

### ISSUE THREAD

**Issue by AndrewthepikaDev** [xenondevs/Nova#315]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.15-alpha8

### Nova Addons and Versions

None

### Expected behavior

Make a Nova addon with latest builds in IntelliJ, build the addon, and it works.

### Observed/Actual behavior

Invalid line: <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Log in - SpigotMC Stash</title><script>

### Steps to reproduce

1. Make a new Nova addon on IntelliJ
2. Build the addon.

### Server log

Not on a server

### Errors

```log
Invalid line: <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Log in - SpigotMC Stash</title><script>
```

### Additional context

just trying to build a nova addon help

**Comment by NichtStudioCode** [comment]
I cannot reproduce this. Are you using the latest addon template? And have you tried running gradle clean?

**Comment by destial** [comment]
When trying to build Nova, I get the same error.
![image](https://github.com/xenondevs/Nova/assets/67675805/c6bf3173-ef53-4269-8804-d7036f63c8c1)
